from __future__ import annotations

import os
from pathlib import Path

os.environ.setdefault("HF_HUB_DISABLE_XET", "1")

DEFAULT_SAMPLE_RATE = 44_100
TRANSCRIPTION_SAMPLE_RATE = 16_000
DEFAULT_OUTPUT_FORMAT = "wav"
DEFAULT_MODE = "auto"
DEFAULT_DEVICE = "auto"
DEFAULT_TRANSCRIPTION_LANGUAGE = "zh"
DEFAULT_TRANSCRIPTION_ASR_MODEL = "small"
DEFAULT_MUSIC_BACKEND = "demucs"
DEFAULT_DIALOGUE_BACKEND = "cdx23"
DEFAULT_TRANSLATION_BACKEND = "local-m2m100"
DEFAULT_TRANSLATION_SOURCE_LANG = "zh"
DEFAULT_TRANSLATION_TARGET_LANG = "en"
DEFAULT_TRANSLATION_LOCAL_MODEL = "facebook/m2m100_418M"
DEFAULT_TRANSLATION_BATCH_SIZE = 4
DEFAULT_CONDENSE_MODE = "off"
DEFAULT_DUBBING_BACKEND = "qwen3tts"
DEFAULT_DUBBING_BACKREAD_MODEL = "tiny"
DEFAULT_PIPELINE_RUN_FROM_STAGE = "stage1"
DEFAULT_PIPELINE_RUN_TO_STAGE = "task-e"
DEFAULT_PIPELINE_OUTPUT_ROOT = "output-pipeline"
DEFAULT_PIPELINE_WRITE_STATUS = True
DEFAULT_PIPELINE_STATUS_UPDATE_INTERVAL_SEC = 2.0
DEFAULT_RENDER_FIT_POLICY = "conservative"
DEFAULT_RENDER_FIT_BACKEND = "atempo"
DEFAULT_RENDER_MIX_PROFILE = "preview"
DEFAULT_RENDER_DUCKING_MODE = "static"
DEFAULT_RENDER_OUTPUT_SAMPLE_RATE = 24_000
DEFAULT_RENDER_BACKGROUND_GAIN_DB = -8.0
DEFAULT_RENDER_WINDOW_DUCKING_DB = -3.0
DEFAULT_RENDER_PREVIEW_FORMAT = "wav"
DEFAULT_DELIVERY_CONTAINER = "mp4"
DEFAULT_DELIVERY_VIDEO_CODEC = "copy"
DEFAULT_DELIVERY_AUDIO_CODEC = "aac"
DEFAULT_DELIVERY_AUDIO_BITRATE = "192k"
DEFAULT_DELIVERY_END_POLICY = "trim_audio_to_video"
DEFAULT_SILICONFLOW_BASE_URL = os.environ.get("SILICONFLOW_BASE_URL", "https://api.siliconflow.cn/v1")
DEFAULT_SILICONFLOW_MODEL = os.environ.get("SILICONFLOW_MODEL", "deepseek-ai/DeepSeek-V3")
DEFAULT_SUBTITLE_MODE = "none"
DEFAULT_SUBTITLE_SOURCE = "ocr"
DEFAULT_SUBTITLE_FONT_CJK = "Noto Sans CJK SC"
DEFAULT_SUBTITLE_FONT_LATIN = "Noto Sans"
DEFAULT_SUBTITLE_PRIMARY_COLOR = "#FFFFFF"
DEFAULT_SUBTITLE_OUTLINE_COLOR = "#000000"
DEFAULT_SUBTITLE_OUTLINE_WIDTH = 2.0
DEFAULT_SUBTITLE_SHADOW_DEPTH = 1.0
DEFAULT_SUBTITLE_PREVIEW_DURATION_SEC = 10
SUPPORTED_OUTPUT_FORMATS = {"wav", "mp3", "flac", "aac", "opus"}
OUTPUT_ROOT = Path("output")
CACHE_ROOT = Path(
    os.environ.get(
        "TRANSLIP_CACHE_DIR",
        Path.home() / ".cache" / "translip",
    )
)
